### ISSUE TITLE
RTT min/max/average

### ISSUE THREAD

**Issue by PedroPerezMSFT** [pjperez/httping#3]
Right now httping only shows the average RTT. It would be helpful to include min and max too.

Or maybe include median instead of average and show results for "max time for 100%, 90%, 50%, 25% of requests", e.g.:

100% were faster than 500ms
90% were faster than 250ms
50% were faster than 210ms
25% were faster than 190ms

It would give a better idea of the overall results. A min and a max could be outliers (especially the "max" value, as httping needs to establish the TCP session at first, then it just reuses that for all the queued requests).

**Comment by pjperez** [comment]
Median, max, min and percentile added. Closing Issue.
