### ISSUE TITLE
Redirections are followed but not accounted for

### ISSUE THREAD

**Issue by pjperez** [pjperez/httping#7]
If we get e.g. a 301 we will follow the redirection until we get either a good (200) or bad (400, 500, ...) response, however we're not reflecting that on the results, thus showing increased RTT.

It makes sense to show the total RTT, however we should be showing a flag that says we've followed a redirect.

**Comment by TAbdiukov** [comment]
I addressed this bug in #16

**Comment by TAbdiukov** [comment]
UPDATE: Never mind, you want to follow redirects, but show this information, but show it to the user, right? (Instead of ignoring them?)

**Comment by pjperez** [comment]
Fixed by @TAbdiukov on https://github.com/pjperez/httping/pull/16, thank you!
