### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by xmha97** [pjperez/httping#9]
Can I set HTTP proxy?

**Comment by pjperez** [comment]
It's been a while since I've touched this, but I don't think so. I don't even think it would follow OS settings for proxy. I am planning on reviewing this project in a few weeks, I'll check if I can add this as a feature. Thank you!

**Comment by TAbdiukov** [comment]
The program does NOT respect proxy settings, at least on Windows

**Comment by TAbdiukov** [comment]
Addressed in my PR. Please see: #13 and upcoming all-encompassing #15 

* PR that adds proxy support only: #13  
* All-encompassing PR that adds additional nice things for using httping: #15 

I also made a fork with proxy support and all other nice features here: **[TAbdiukov/httping-proxy](https://github.com/TAbdiukov/httping-proxy)**

**Comment by pjperez** [comment]
Hi @TAbdiukov , thanks a lot for the changes, they are really appreciated. Although I am happy with your changes as they are, I have left some comments for your consideration. Let me know your thoughts and we can proceed to merge the changes.

Also thank you for forking the project. It is extremely cool to see someone building on top of this old project.

**Comment by pjperez** [comment]
Closing as completed, thanks @TAbdiukov 

https://github.com/pjperez/httping/pull/15
